robot can handle GetPIDGains packet and send values back
RoboTeamTwente/roboteam_microcontroller4.0 pull request #33
Opened 2022-04-11 15:03 UTC by ejcmd

The robot should be able to send its PID values if it receives a GetPIDGains packet.
This PR relies on [the PR in REM](https://github.com/RoboTeamTwente/roboteam_embedded_messages/pull/9)

2022-04-12 11:09 UTC, skaeringur97 commented on Core/Src/robot.c
> +		robotPIDGains.IbodyX = stateK[0].kI;
Shouldn't these be in the form: stateK[body_x].kP ?

2022-04-12 11:43 UTC, emielsteerneman requested changes

2022-04-12 11:43 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> +	return stateK;
Variable leaving file scope. I suggest doing it like [this](https://github.com/RoboTeamTwente/roboteam_microcontroller4.0/blob/4516897d9af3a64fe50f52cefcb82164405deb86/Core/Src/wheels.c#L200)

2022-04-12 11:43 UTC, emielsteerneman commented on Core/Src/wheels.c
> +	return wheelsK;
variable leaving file scope

2022-04-15 01:02 UTC, emielsteerneman commented
Implemented transmission of packets in the development branch. Just needs the right PID values instead of the placeholder values

2022-04-15 01:02 UTC, closed without merging