Feature/consistent control conventions
RoboTeamTwente/roboteam_microcontroller4.0 pull request #64
Opened 2023-01-13 14:35 UTC by supertom01

All the mathematical steps that convert a given velocity and angle into wheel speeds and vice versa have been updated in order to match the notation and logic that has been used on the [wiki](https://wiki.roboteamtwente.nl/technical/control/omnidirectional).

This code has been tested on the robot hardware and does not show any unexpected behavior.

2023-01-14 14:54 UTC, skaeringur97 commented on Core/Inc/Util/control_util.h
> +	wheels_RB,	// The right back wheel
I agree with this change, but be careful that if python utils, AI code etc sends or reads data to/from the wheels that you change it there also

2023-01-14 14:56 UTC, skaeringur97 approved these changes
Looks good! Just make sure it´s easy to find the reasoning for this on the wiki. Since this has been tested, I think it can be merged (as long as my other comment is checked first)

2023-01-16 11:19 UTC, supertom01 commented on Core/Inc/Util/control_util.h
> +	wheels_RB,	// The right back wheel
Ah yes indeed. I did not think about that.

2023-01-16 12:38 UTC, supertom01 commented on Core/Inc/Util/control_util.h
> +	wheels_RB,	// The right back wheel
The compatibility with the new wheel order is updated in the basestation with the next PR: RoboTeamTwente/Basestation#29. 

For AI I could not find any references to direct wheel speeds

2023-01-16 13:07 UTC, skaeringur97 commented on Core/Inc/Util/control_util.h
> +	wheels_RB,	// The right back wheel
If you want to be extra careful you can disconnect all wheels except one and read plot the wheel speeds for each wheel respectively.

2023-01-16 14:44 UTC, emielsteerneman requested changes
All in all, looks good! Using `local` and `global` as well as `u` and `v` makes the code much more readable. Nice that you also tested it. I have some minor requests if you have the time, plus one or two actual things that need fixing.

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Inc/Control/stateControl.h
>  void stateControl_SetState(float input[4]);
Request to change `input` to `stateLocal`

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> +// The current global u, v, w and yaw velocities.
This should say `local` I assume

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
>  static PIDvariables stateK[4];
Request to change this to `stateLocalK`

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> +static void body2Wheels(float wheelSpeed[4], float localState[3]);
Please stick to `stateLocal / stateGlobal` or `localState / globalState`. My preference goes to the first.

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> + * @param angle 	Yaw
We should choose some good definitions for yaw and angle. We have two angles on the robot; The direction the robot is looking at, and the direction the robot is moving towards. This function description says that `angle` == `yaw` which is confusing, at least to me. Any idea if we already have clear definitions?

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> +static void velocityControl(float localState[3], float stateGlobalRef[4], float velocityWheelRef[4]);
Same request, either `state...` or `...State`, with preference towards `state...`

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
>  void stateControl_SetState(float input[4]){
request to change to `stateLocal` or `_stateLocal` or smth

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> +	gains[vel_u].kP = stateK[vel_u].kP;
I think I already mentioned this but if possible change to `stateLocal`

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> +	wheelSpeed[wheels_RF] = vel[vel_u] * D[0] + vel[vel_v] * D[1];
Is it possible to replace these indices (0, 1, 2, ...) with Enums or defines?

2023-01-16 14:44 UTC, emielsteerneman commented on Core/Src/robot.c
> +		float vu = stateEstimation_GetState()[vel_u];
I am not a fan of multiple function calls, nor that `stateLocal` leaves the `stateEstimation` file scope by returning a pointer. But, it's not critical.

2023-01-16 16:08 UTC, supertom01 commented
It seems like that robot feedback is being incorrectly calculated at the moment. Hence, do not merge yet!

2023-01-17 15:17 UTC, supertom01 commented on Core/Src/Control/stateControl.c
> + * @param angle 	Yaw
Yeah there is at this moment not a strict definition yet indeed.

So in the code the `yaw` should technically always indicate the local angle of the robot. 
Whereas the `angle` should indicate the global angle of the robot.

2023-01-17 15:34 UTC, supertom01 commented on Core/Src/Control/stateControl.c
> +	wheelSpeed[wheels_RF] = vel[vel_u] * D[0] + vel[vel_v] * D[1];
Not really, or at least I cannot find of any variable names that would any value to these indices.

2023-01-17 15:43 UTC, emielsteerneman commented on Core/Src/Control/stateControl.c
> + * @param angle 	Yaw
with angle, do you mean the facing direction or the driving direction?

2023-01-19 13:51 UTC, supertom01 commented on Core/Src/Control/stateControl.c
> + * @param angle 	Yaw
The angle as in the facing direction. 

If we are talking about any angle at all in robot code, we're actually always talking about our facing direction. The only location where the driving direction is used is the x- and y- decomposition section, happening straight away in `robot.c`. 

https://github.com/RoboTeamTwente/roboteam_microcontroller5.0/blob/dba96402ebf50d9e8b2bfea6c3d334adc2a7d709/Core/Src/robot.c#L174-L180

2023-02-02 17:14 UTC, casdoorn approved these changes
LGTM, in the future it might be nice to convert some of the float arrays into structs to remove magic indices and make sure that at compile time all function calls can be checked for correct inputs and prevent out-of-bounds indexing.
For D and Dinv you can use float[m][n] definitions to make them actual matrices, if that makes it easier to name things. Or use the multiplyMatrix function in body2wheels/wheels2body.

None of these are blockers and are more suggestions for further cleanup, so feel free to merge.

2023-02-02 17:58 UTC, emielsteerneman approved these changes
Lgtm

2023-02-02 17:59 UTC, merged